### ISSUE TITLE
Memory Limits Problem

### ISSUE THREAD

**Issue by NearZhxiAo** [andoum/object_detector_6d#1]
Hello~
  I'm a master student in China , sorry for my poor English...
  I was using your code with dataset provided in `http://www.iis.ee.ic.ac.uk/rkouskou/research/6D_NBV.html`

But there is a problem when run `train_forest.sh` , 
I `strace` the process and it seems that the process read all patches data into memory , and my computer has only 16G memory ...

I want to know that what is the `basic hardware support ` to run this code? 

Thanks..

**Comment by andoum** [comment]
Unfortunately this is a limitation of the current Random Forest implementation. I used to train it on a workstation with 256GB of RAM, but generally it depends on how many objects/training patches you use.

**Comment by NearZhxiAo** [comment]
Thanks... I think I should train it on a workstation too :)
